"""Professional PDF report for a Cadence screening result.

Deliberately plain and clinical (not the kawaii web styling) so it is suitable for
printing / offline records. Built with fpdf2 (core Helvetica font, latin-1 safe).
"""
from __future__ import annotations

import datetime as _dt

from fpdf import FPDF
from fpdf.enums import XPos, YPos

NAVY = (31, 42, 68)
GRAY = (90, 96, 112)
LIGHT = (240, 242, 247)
LINE = (210, 214, 224)
BAND_COLOR = {"low": (26, 138, 90), "moderate": (176, 132, 11), "elevated": (192, 57, 43)}
BAND_TEXT = {
    "low": "Speech patterns are consistent with healthy controls.",
    "moderate": "Some speech patterns are atypical; interpret with caution.",
    "elevated": "Several speech patterns resemble those associated with Parkinson's "
                "disease. This is a screening signal only, not a diagnosis.",
}


def _latin1(s: str) -> str:
    return str(s).encode("latin-1", "replace").decode("latin-1")


class _Report(FPDF):
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, self.w, 22, "F")
        self.set_xy(15, 6)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 10, "Cadence  |  Voice Screening Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_y(24)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 6, _latin1("Generated by Cadence - research prototype, not a medical device "
                                "- github.com/ahammadshawki8/CADENCE"),
                  align="C")


def _section(pdf, title):
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, _latin1(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*LINE)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(2)


def build_pdf(result: dict) -> bytes:
    pdf = _Report(format="A4")
    pdf.set_auto_page_break(True, margin=16)
    pdf.add_page()
    pdf.set_x(pdf.l_margin)

    pct = round(result.get("probability_pd", 0) * 100)
    band = result.get("risk_band", "low")
    bc = BAND_COLOR.get(band, NAVY)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 5, _latin1("Report generated: " + _dt.datetime.now().strftime("%Y-%m-%d %H:%M")),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ---- result summary box ----
    _section(pdf, "Screening result")
    y0 = pdf.get_y()
    pdf.set_fill_color(*LIGHT)
    pdf.rect(pdf.l_margin, y0, pdf.w - pdf.l_margin - pdf.r_margin, 26, "F")
    pdf.set_xy(pdf.l_margin + 4, y0 + 4)
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(*bc)
    pdf.cell(34, 12, f"{pct}%")
    pdf.set_xy(pdf.l_margin + 42, y0 + 4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, _latin1(f"Screening indicator  -  band: {band.upper()}"),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_xy(pdf.l_margin + 42, y0 + 12)
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 46, 4.5, _latin1(BAND_TEXT.get(band, "")))
    pdf.set_y(y0 + 30)

    # indicator bar
    bw = pdf.w - pdf.l_margin - pdf.r_margin
    pdf.set_fill_color(*LINE); pdf.rect(pdf.l_margin, pdf.get_y(), bw, 4, "F")
    pdf.set_fill_color(*bc); pdf.rect(pdf.l_margin, pdf.get_y(), bw * pct / 100, 4, "F")
    pdf.ln(8)

    # ---- humane summary ----
    if result.get("narrative"):
        _section(pdf, "Summary")
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(*GRAY)
        pdf.multi_cell(0, 5, _latin1(result["narrative"]))
        pdf.ln(1)

    # ---- contributing biomarkers ----
    _section(pdf, "Contributing voice biomarkers")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*NAVY)
    pdf.cell(118, 7, "Biomarker", border="B")
    pdf.cell(30, 7, "Direction", border="B")
    pdf.cell(0, 7, "Impact", border="B", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    maxs = max((abs(f["shap"]) for f in result.get("top_factors", [])), default=1) or 1
    for f in result.get("top_factors", []):
        pd = f["shap"] > 0
        pdf.set_text_color(*GRAY)
        pdf.cell(118, 6, _latin1(f["label"][:70]))
        pdf.set_text_color(*(BAND_COLOR["elevated"] if pd else BAND_COLOR["low"]))
        pdf.cell(30, 6, "Parkinson's" if pd else "healthy")
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 6, f"{abs(f['shap']) / maxs * 100:.0f}%", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ---- acoustic measurements ----
    _section(pdf, "Acoustic measurements")
    rep = result.get("acoustic_report", [])
    col_w = (pdf.w - pdf.l_margin - pdf.r_margin) / 2
    pdf.set_font("Helvetica", "", 9)
    for i in range(0, len(rep), 2):
        for j in (0, 1):
            if i + j < len(rep):
                item = rep[i + j]
                pdf.set_text_color(*GRAY)
                pdf.cell(col_w * 0.62, 6, _latin1(item["label"]))
                pdf.set_text_color(*NAVY)
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(col_w * 0.38, 6, _latin1(f"{item['value']}"))
                pdf.set_font("Helvetica", "", 9)
        pdf.ln(6)

    # ---- methodology + disclaimer ----
    _section(pdf, "Method & disclaimer")
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(0, 4.5, _latin1(
        "Cadence estimates a screening indicator from language-independent acoustic biomarkers "
        "(pitch variability, jitter, shimmer, harmonics-to-noise ratio, articulation rate, pausing) "
        "using a logistic model trained on pooled Italian and MDVR-KCL reading recordings and "
        "validated across datasets (external AUC ~0.72). Contributions are attributed with SHAP."))
    pdf.ln(1)
    pdf.set_text_color(*BAND_COLOR["elevated"])
    pdf.set_font("Helvetica", "B", 9)
    pdf.multi_cell(0, 4.8, _latin1(result.get("disclaimer", "")))

    out = pdf.output()
    return bytes(out)


if __name__ == "__main__":
    import sys, json
    sys.path.insert(0, ".")
    demo = {"probability_pd": 0.89, "risk_band": "elevated", "threshold": 0.5,
            "top_factors": [{"label": "Proportion of silence and pausing", "shap": 1.2, "value": 0.54},
                            {"label": "Harmonics-to-noise ratio", "shap": -0.8, "value": -6.0}],
            "acoustic_report": [{"label": "Jitter", "value": 0.05}, {"label": "Shimmer", "value": 0.2}],
            "disclaimer": "Cadence is a research prototype and screening aid, NOT a medical device."}
    open("artifacts/_demo_report.pdf", "wb").write(build_pdf(demo))
    print("wrote artifacts/_demo_report.pdf")
